<table border="0" style="width:100%">
 <tr>
    <td>
        <img src="https://static-frm.ie.edu/university/wp-content/uploads/sites/6/2022/06/IE-University-logo.png" width=150>
     </td>
    <td><div style="font-family:'Courier New'">
            <div style="font-size:25px">
                <div style="text-align: right"> 
                    <b> MASTER IN BIG DATA</b>
                    <br>
                    Python for Data Analysis II
                    <br><br>
                    <em> Daniel Sierra Ramos </em>
                </div>
            </div>
        </div>
    </td>
 </tr>
</table>

# **S09: EXERCISES**

## Exercise 01

Recover the Exercise 01 from Session 07
1. Build the model again but now include cross validation in the training process using `KFold` cross validation
1. Calculate the precision, recall and f1 for each fold and represent the results in a chart. Use 5 folds.
1. Is your model robust? How can you improve it?
1. Now train your model with the entire training set and evaluate it with the test set. How does it perform?

In [16]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.svm import SVC

In [17]:
data = pd.read_csv("../Session_07/data/adult.csv.zip")
data.shape

(48842, 15)

In [18]:
#split into train and test
X = data.drop(columns = "income")
y = data["income"]
X_train, X_test, y_train, y_test = train_test_split(X.loc[:1000], y.loc[:1000], test_size=0.33, random_state=42)

In [19]:
ohe = OneHotEncoder(sparse=False)

In [20]:
#select categorical data
X_train_cat = X_train.select_dtypes("O")
X_train_cat_ohe = ohe.fit_transform(X_train_cat)
X_train_cat_ohe

c:\Users\santi\code\uni_env\lib\site-packages\sklearn\preprocessing\_encoders.py:828: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0., 0., 0., ..., 0., 0., 1.],
       [1., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [21]:
ohe.categories_[1]

array(['10th', '11th', '12th', '1st-4th', '5th-6th', '7th-8th', '9th',
       'Assoc-acdm', 'Assoc-voc', 'Bachelors', 'Doctorate', 'HS-grad',
       'Masters', 'Preschool', 'Prof-school', 'Some-college'],
      dtype=object)

In [22]:
X_train_cat_ohe = pd.DataFrame(X_train_cat_ohe, columns=ohe.get_feature_names_out())

In [23]:
X_train_full = pd.concat([X_train.reset_index(), X_train_cat_ohe], axis=1)

In [24]:
X_train_full = X_train_full.drop(columns=X_train_cat.columns)

In [25]:
X_train_full

index  age  fnlwgt  educational-num  capital-gain  capital-loss  \
0      311   22  197200               10             0             0   
1      765   17  143331                7             0             0   
2      630   55  126840               10             0             0   
3        0   25  226802                7             0             0   
4      316   20  318865               10             0             0   
..     ...  ...     ...              ...           ...           ...   
665    106   41  201520                9             0             0   
666    270   25  177221                9             0             0   
667    860   46   96652               11             0             0   
668    435   62   71467               14             0             0   
669    102   22  212261               10             0             0   

     hours-per-week  workclass_?  workclass_Federal-gov  workclass_Local-gov  \
0                40          0.0                    0.0                  0.0   
1                40          1.0                    0.0                  0.0   
2                40          0.0                    0.0                  0.0   
3                40          0.0                    0.0                  0.0   
4                40          1.0                    0.0                  0.0   
..              ...          ...                    ...                  ...   
665              40          0.0                    0.0                  1.0   
666              75          0.0                    0.0                  0.0   
667              40          0.0                    0.0                  0.0   
668              40          0.0                    0.0                  0.0   
669              39          0.0                    0.0                  0.0   

     ...  native-country_Japan  native-country_Laos  native-country_Mexico  \
0    ...                   0.0                  0.0                    0.0   
1    ...                   0.0                  0.0                    0.0   
2    ...                   0.0                  0.0                    0.0   
3    ...                   0.0                  0.0                    0.0   
4    ...                   0.0                  0.0                    0.0   
..   ...                   ...                  ...                    ...   
665  ...                   0.0                  0.0                    0.0   
666  ...                   0.0                  0.0                    0.0   
667  ...                   0.0                  0.0                    0.0   
668  ...                   0.0                  0.0                    0.0   
669  ...                   0.0                  0.0                    0.0   

     native-country_Philippines  native-country_Poland  \
0                           0.0                    0.0   
1                           0.0                    0.0   
2                           0.0                    0.0   
3                           0.0                    0.0   
4                           0.0                    0.0   
..                          ...                    ...   
665                         0.0                    0.0   
666                         0.0                    0.0   
667                         0.0                    0.0   
668                         0.0                    0.0   
669                         0.0                    0.0   

     native-country_Portugal  native-country_Puerto-Rico  \
0                        0.0                         0.0   
1                        0.0                         0.0   
2                        0.0                         0.0   
3                        0.0                         0.0   
4                        0.0                         0.0   
..                       ...                         ...   
665                      0.0                         0.0   
666                      0.0                         0.0   
667  

Let's use `Cross Validation`.

In [31]:
# Train and evaluate on test set
clf = SVC(kernel='linear', C=1)

In [32]:
# Train and evalute ion training set
cross_val_score(clf, X_train_full, y_train, cv=5, scoring="precision")

TypeError: cross_val_score() got an unexpected keyword argument 'pos_label'

Let's use `KFold`.

In [ ]:
from sklearn.model_selection import LeaveOneOut, KFold

Calculate `precision` metric.

In [ ]:
# Train and evalute ion training set
cross_val_score(clf, X_train_full, y_train, cv=5, scoring="precision")

array([0.95348837, 0.95348837, 0.95238095, 0.97619048, 1.        ])

Caculate `recall` metric.

In [37]:
# Train and evalute ion training set
cross_val_score(clf, X_train_full, y_train, cv=5, scoring="recall")

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done   2 out of   5 | elapsed:    5.9s remaining:    8.8s
[Parallel(n_jobs=-1)]: Done   5 out of   5 | elapsed:    5.9s finished


ValueError: 
All the 5 fits failed.
It is very likely that your model is misconfigured.
You can try to debug the error by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
5 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\santi\code\uni_env\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
TypeError: BaseLibSVM.fit() got an unexpected keyword argument 'pos_label'


Caculate `f1score` metric.

In [ ]:
# Train and evalute ion training set
cross_val_score(clf, X_train, y_train, cv=5, scoring="f1")

array([0.95348837, 0.95348837, 0.95238095, 0.97619048, 1.        ])

Let's build the `Logistic Regression` model.

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()

In [ ]:
lr.fit(X_train_full, y_train)

LogisticRegression()

In [ ]:
X_test_cat = X_test.select_dtypes("O")
X_test_ohe = ohe.transform(X_test_cat)
X_test_ohe = pd.DataFrame(X_test_ohe, columns=ohe.get_feature_names_out())

In [ ]:
X_test_full = pd.concat([X_test.reset_index(), X_test_ohe], axis=1)
X_test_full = X_test_full.drop(columns=X_test_cat.columns)

In [ ]:
lr.predict(X_test_full)

array(['<=50K', '<=50K', '>50K', ..., '<=50K', '<=50K', '<=50K'],
      dtype=object)

In [ ]:
lr.score(X_test_full, y_test)

0.8045663233651817